force-app/main/default/objects/Compliance_Check__c/Compliance_Check__c.object-meta.xml
<CustomObject>
    <description>Manage background check process by compliance team.</description>
    <label>Compliance Check</label>
    <nameField>
        <displayFormat>CC-{0000}</displayFormat>
        <label>Compliance Check Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Compliance Checks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Compliance_Check__c/fields/Completion_Date__c.field-meta.xml
<CustomField>
    <fullName>Completion_Date__c</fullName>
    <description>Date that the compliance check was completed.</description>
    <inlineHelpText>Date that the compliance check was completed.</inlineHelpText>
    <label>Completion Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Compliance_Check__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <description>Subject of compliance check</description>
    <inlineHelpText>Subject of compliance check</inlineHelpText>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Compliance Checks</relationshipLabel>
    <relationshipName>Compliance_Check</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Compliance_Check__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of compliance check.</description>
    <inlineHelpText>Status of compliance check.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Requested</fullName>
                <default>true</default>
                <label>Requested</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TA_ComplianceCheck_CompletedNotification.cls
public class TA_ComplianceCheck_CompletedNotification implements TriggerAction.BeforeUpdate {
	@TestVisible
    private static final String COMPLETED = 'Completed';
    
    public void beforeUpdate (List<Compliance_Check__c> newList, List<Compliance_Check__c> oldList) { 
    	
        List<Compliance_Check_Completed__e> completedEvents = new List<Compliance_Check_Completed__e>();

        for (Compliance_Check__c cc : newList) {

            if (cc.Status__c == COMPLETED) {
                Compliance_Check_Completed__e completedEvent = new Compliance_Check_Completed__e(
                    Learner_External_Id__c = cc.Contact__c,
                    Completed_Date__c = cc.Completion_Date__c
                );

                completedEvents.add(completedEvent);
            }
        }

        if (!completedEvents.isEmpty()) {
            EventBus.publish(completedEvents);
        }
    }
}