force-app/main/default/objects/Compliance_Check__c/Compliance_Check__c.object-meta.xml
<CustomObject>
    <description>Manage background check process by compliance team.</description>
    <label>Compliance Check</label>
    <nameField>
        <displayFormat>CC-{0000}</displayFormat>
        <label>Compliance Check Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Compliance Checks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Compliance_Check__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <description>Subject of compliance check</description>
    <inlineHelpText>Subject of compliance check</inlineHelpText>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Compliance Checks</relationshipLabel>
    <relationshipName>Compliance_Check</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Compliance_Check__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of compliance check.</description>
    <inlineHelpText>Status of compliance check.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Requested</fullName>
                <default>true</default>
                <label>Requested</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TA_Contact_RequestComplianceCheck.cls
public with sharing class TA_Contact_RequestComplianceCheck implements TriggerAction.AfterInsert {
    
    @TestVisible
    private static final String REQUESTED = 'Requested';

    public void afterInsert(List<Contact> newList){
        List<Compliance_Check__c> ccList = new List<Compliance_Check__c>();
        for (Contact con : newList) {
          Compliance_Check__c cc = new Compliance_Check__c (Contact__c = con.id, Status__c = REQUESTED);
          ccList.add(cc);
        }

        if (!ccList.isEmpty()) {
            insert ccList;
        }
      }
}